sudo: false
language: node_js
before_script:
  - sleep 15
os:
  - linux
node_js:
  - '8'
  - '10'
  - '12'
services:
  - mongodb
after_success: npm run codeclimate
notifications:
  email:
    on_success: never
